export { useCreateImage } from "./queryHooks";
export { useCreateSeries } from "./queryHooks";
export { useDeleteSeriesById } from "./queryHooks";
export { useDeleteMultipleSeriesByIdz } from "./queryHooks";
export { useUpdateSeries } from "./queryHooks";
export { useGetSeriesDetailsById } from "./queryHooks";
export { useGetManagerSeriesForTable } from "./queryHooks";

export type { CreateImageInput } from "./queryHooks.types";
export type { GetManagerSeriesForTableInput } from "./queryHooks.types";
export type { CreateSeriesInput } from "./queryHooks.types";
export type { CreateAdditionalInfoInput } from "./queryHooks.types";
export type { UpdateImageInput } from "./queryHooks.types";
export type { CreateMediaBasicInfoInput } from "./queryHooks.types";
export type { DeleteSeriesByIdParams } from "./queryHooks.types";
export type { UpdateSeriesInput } from "./queryHooks.types";
export type { SeriesIdParams } from "./queryHooks.types";
export type { GetMediaBasicInfoByMediaIdParams } from "./queryHooks.types";
export type { DeleteMultipleSeriesByIdzParams } from "./queryHooks.types";
export type { ImageIdOutput } from "./queryHooks.types";
export type { GetManagerSeriesForTableOutput } from "./queryHooks.types";
export type { DeleteSeriesByIdOutput } from "./queryHooks.types";
export type { DeleteMultipleSeriesByIdzOutput } from "./queryHooks.types";
export type { UpdateSeriesOutput } from "./queryHooks.types";
