export enum MovierMediaEnum {
  SERIES = "Series",
  SEASON = "Season",
  EPISODE = "Episode",
  TRAILER = "Trailer",
  SHORT = "Short",
  MOVIE = "Movie",
}

export enum GenderEnum {
  FEMALE = "Female",
  MALE = "Male",
}

export enum MediaCountriesEnum {
  USA = "United States of America",
  AUSTRALIA = "Australia",
  AUSTRIA = "Austria",
  AFGHANISTAN = "Afghanistan",
  CANADA = "Canada",
  CHINA = "China",
  REPUBLIC_OF_CHINA = "Republic of China",
  FRANCE = "France",
  GERMANY = "Germany",
  INDIA = "India",
  INDONESIA = "Indonesia",
  IRAN = "Iran",
  IRAQ = "Iraq",
  ITALY = "Italy",
  JAPAN = "Japan",
  NORTH_KOREA = "North korea",
  SOUTH_KOREA = "South korea",
  MEXICO = "Mexico",
  NETHERLANDS = "Netherlands",
  NEW_ZEALAND = "New zealand",
  PAKISTAN = "Pakistan",
  RUSSIAN_FEDERATION = "Russian Federation",
  SINGAPORE = "Singapore",
  SPAIN = "Spain",
  SWITZERLAND = "Switzer land",
  THAILAND = "Thailand",
  TURKEY = "Turkey",
  UNITED_KINGDOM = "United kingdom",
  YEMEN = "Yemen",
  ZIMBABWE = "Zimbabwe",
}

export enum LanguagiesEnum {
  ENGLISH = "English",
  GERMAN = "German",
  PERSIAN = "Persian",
  CHINESE = "Chinese",
  FRENCH = "French",
  HINDI = "Hindi",
  INDONESIAN = "Indonesian",
  ARABIC = "Arabic",
  ITALIAN = "Italian",
  JAPANESE = "Japanese",
  KOREAN = "Korean",
  SPANISH = "Spanish",
  DUTCH = "Dutch",
  URDU = "Urdu",
  RUSSIAN = "Rassian",
  THAI = "Thai",
  TURKISH = "Turkish",
}

export enum CineastProfessionEnum {
  PRODUCER = "Producer",
  DIRECTOR = "Director",
  WRITER = "Writer",
  ACTOR = "Actor",
  ACTRESS = "Actress",
  CINEMATOGRAPHER = "Cinematographer",
  EDITOR = "Editor",
  COSTUME_DESIGNER = "Costume Designer",
  MAKEUP_ARTIST = "Makeup Artist",
  SOUND_ENGINEER = "Sound Engineer",
  VISUAL_EFFECTS_ARTIST = "Visual Effects Artist",
  STUNT_PERFORMER = "Stunt Performer",
  PRODUCTION_MANAGER = "Production Manager",
  SET_DESIGNER = "Set Designer",
  SCRIPT_SUPERVISOR = "Script Supervisor",
  DISTRIBUTOR = "Distributor",
  MARKETING_MANAGER = "Marketing Manager",
  FILM_CRITIC = "Film Critic",
  CASTING_DIRECTOR = "Casting Director",
  LOCATION_MANAGER = "Location Manager",
  POST_PRODUCTION_SUPERVISOR = "Post Production Supervisor",
  SCREENWRITER = "Screenwriter",
  EXECUTIVE_PRODUCER = "Executive Producer",
  CAMERA_OPERATOR = "Camera Operator",
}

export enum ImageVariantEnum {
  BACKDROP = "Backdrop",
  THUMBNAIL = "Thumbnail",
  PROFILE = "Profile",
}

export enum MediaGenriesEnum {
  ACTION = "Action",
  DRAMA = "Drama",
  COMEDY = "Comedy",
  FASTASY = "Fantasy",
  HORROR = "Horror",
  ROMANCE = "Romance",
  ADVANTURE = "Aventure",
  WAR = "War",
  BIO_GRAPHY = "Biography",
  SUPER_HERO = "Super Hero",
}

export enum MediaStatusEnum {
  RELEASED = "Released",
  IN_PRODUCTION = "In Production",
  POST_PRODUCTION = "Post Production",
  ON_HOLD = "On Hold",
  CANCELED = "Canceled",
}
