export enum CineastProfessionEnum {
  PRODUCER = "Producer",
  DIRECTOR = "Director",
  WRITER = "Writer",
  ACTOR = "Actor",
  ACTRESS = "Actress",
  CINEMATOGRAPHER = "Cinematographer",
  EDITOR = "Editor",
  COSTUME_DESIGNER = "Costume Designer",
  MAKEUP_ARTIST = "Makeup Artist",
  SOUND_ENGINEER = "Sound Engineer",
  VISUAL_EFFECTS_ARTIST = "Visual Effects Artist",
  STUNT_PERFORMER = "Stunt Performer",
  PRODUCTION_MANAGER = "Production Manager",
  SET_DESIGNER = "Set Designer",
  SCRIPT_SUPERVISOR = "Script Supervisor",
  DISTRIBUTOR = "Distributor",
  MARKETING_MANAGER = "Marketing Manager",
  FILM_CRITIC = "Film Critic",
  CASTING_DIRECTOR = "Casting Director",
  LOCATION_MANAGER = "Location Manager",
  POST_PRODUCTION_SUPERVISOR = "Post Production Supervisor",
  SCREENWRITER = "Screenwriter",
  EXECUTIVE_PRODUCER = "Executive Producer",
  CAMERA_OPERATOR = "Camera Operator",
}
